
stages:
  - Deploy

Deploy to Dev:
  stage: Deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "Gitlab CI"
    - git config --global push.default matching
  environment:
    name: release
  only:
    - master
  #when: manual
  script:
    - ssh $SSH_USER@$SSH_IP "$(pwd)";
