stages:
  - Deploy

Deploy to Dev:
  stage: Deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "Gitlab CI"
    - git config --global push.default matching
  environment:
    name: release
  only:
    - develop
  #when: manual
  script:
    - ssh stolaf_dev "cd webapps/bridge-dev/wp-content/themes/bridgelibrary-theme && git checkout develop && git pull --ff-only origin develop && exit";
    - ssh stolaf_dev "cd webapps/bridge-dev/wp-content/themes/bridgelibrary-theme && npm install"
    - ssh stolaf_dev "cd webapps/bridge-dev/wp-content/themes/bridgelibrary-theme && npm build run"
