name: build-assets

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-assets-develop:
    name: Build assets for staging server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: NPM Build
        run: |
          npm ci
          npm run build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'build staging assets'
          pull: -v
          add: 'assets/* --force'
  build-assets-production:
    name: Build assets for production server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: NPM Build
        run: |
          npm ci
          npm run build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'build production assets'
          pull: -v
          add: 'assets/* --force'
